rly_file = "Cambrian.rly"
ttb_files = []
img_files = []
doc_files = [ "README.md",]
release_date = "2026-07-16"
version = "1.0.0"
country_code = "GB"
factual = true
description = ""
year = 2026
display_name = "The Cambrian Line"
name = "The Cambrian Line"
signal_position = "left"
author = "Kristian Zarębski"
contributors = []
