rly_file = "The_Cambrian_Line.rly"
ttb_files = ["The_Cambrian_Line.ttb"]
img_files = ["Cambrian.jpg"]
doc_files = ["README.md"]
release_date = "2026-07-16"
version = "1.0.0"
country_code = "GB"
factual = true
description = "Simulation of The Cambrian Line in Wales, UK"
year = 2026
display_name = "The Cambrian Line"
name = "The Cambrian Line"
signal_position = "left"
author = ""
contributors = []
